name: rollbar_flutter_bump_example
description: Demonstrates how to use the rollbar_flutter plugin.
version: 1.5.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rollbar_flutter_bump: ^1.4.0
  cupertino_icons: ^1.0.0

dependency_overrides:
  rollbar_common_bump:
    path: ../../rollbar_common_bump
  rollbar_dart_bump:
    path: ../../rollbar_dart_bump
  rollbar_flutter_bump:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
