name: rollbar_dart_example
description: Demonstrates how to use rollbar-dart
version: 1.3.0

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  rollbar_dart_bump: ^1.3.0

dependency_overrides:
  rollbar_common_bump:
    path: ../../rollbar_common_bump
  rollbar_dart_bump:
    path: ..

dev_dependencies:
  lints: ^2.0.0
